### ISSUE TITLE
List of selected combinations of latitude and longitude

### ISSUE THREAD

**Issue by JJguri** [JJguri/bestiapop#15]
This functionality will allow bestiapop the generation of MET files using selected combinations of latitude and longitude. The current code is generating complete factorials between the ranges of lat and lon the users pass, i.e. if they select: `-lat "-41.15 -41.05" -lon "145.5 145.6"` bestiapop generates 9 combinations of lat and lon. However, sometimes researchers apply crop masks that define regions within the lattice they are not interested in, e.g. fields where specific crops are not sown. Therefore, for this kind of situation will be good to define a function that allows users to pass a list of lat-lon combinations, so bestiapop will only create MET files for those combinations.

**Comment by darkquasar** [comment]
So regarding this feature request, I don't believe I'm gonna have cycles to include this in BestiaPop 3.0, I've tagged it for BestiaPop 3.1 for future development. 

Since BestiaPop is working as expected, there are some workarounds that the user can implement until we integrate this new feature:

* The user can run BestiaPop multiple times from the command line with only the required lat/lon combinations. 
* The user can `script` the execution of BestiaPop using powershell or bash to run only with the required lat/lon combinations. This is a way of automating it.
* The user can achieve the same results by importing BestiaPop into a Jupyter Notebook and using python to script the process of lat/lon combinations. I will add some very simple documentation on how to use BestiaPop from Jupyter Notebook later.

**Comment by JJguri** [comment]
Ok, so if there are other ways to do that, it would be appreciated to provide the details in the documentation section. Also, it can be stated in some `Enhancements section` or `TODO` this function will be included in BestiaPop 3.1.

**Comment by JJguri** [comment]
@darkquasar do you have some update about it? Today I downloaded a list of 20 lat/lon combinations and took me 15 min to download them one by one. Is there a way to do this automatically without changing too much the code? It will really important enhancement to the current version of bestiapop.

**Comment by darkquasar** [comment]
Hey @JJguri, I've updated the BestiaPop Jupyter Notebook to show how to iterate over combinations of lat/lon, see [this commit](https://github.com/JJguri/bestiapop/commit/4d06797eab8929ae78d46b4c2b7b86fd81805536). I don't think this is a feature needed in the program itself, since it can be easily scripted. 

The only thing required is to pass in a list of lat/lon combinations and iterate over them with a for loop. This can be achieved either with python, bash, cmd, powershell, etc. whatever the shell you execute bestiapop with. 

![image](https://user-images.githubusercontent.com/28435534/107719045-0465de80-6d23-11eb-9b4d-07c98513b822.png)

This list can also be read from a CSV file and converted into a `list of lists` just as the example notebook shows.

If this is what you were after and you're happy with the solution let's please close the issue.

**Comment by JJguri** [comment]
@darkquasar this is great functionality, I was thinking maybe would be good to specify in the example how people can input the csv as a list in the code from a single table with two columns (lat and on) and the code automatically will convert it to a list. This is important for users who do not know too much about how to do that.

**Comment by darkquasar** [comment]
Done, added in the latest commit and README updated. See the new example on how to pass in a CSV with a list. Let me know if it errors out for some reason. NOTE: only single combinations of lat/lon per line are admissible.

**Comment by JJguri** [comment]
the example is applied only through the command line or can be also applied through binder reading the csv?
