### ISSUE TITLE
cannot stop the run with SILO API option

### ISSUE THREAD

**Issue by JJguri** [JJguri/bestiapop#25]
When I was running bestiapop to create a MET file from the cloud, I could not stop the running using Ctrl+C.

**Comment by darkquasar** [comment]
were you running it in *multiprocessing* mode? Unfortunately, BestiaPop had an issue with terminating the program when running in `multicore` mode. I've fixed this now and you should be able to stop BestiaPop when running with `-m` flag. I've tried to stop it when running in standard mode and was able to successfully stop the execution. Please pull latest DEV branch and test again since I wasn't able to reproduce the error.
