### ISSUE TITLE
the csv option is producing two identical files

### ISSUE THREAD

**Issue by JJguri** [JJguri/bestiapop#32]
when the csv option is selected in -ot, bestiapop is generating two identical files in the output folder with different names, for example:

- -41.0-145.0.silo.csv
- bestiapop-beastly-dataframe.csv

Please leave only one, the first one is better due to identifies the name of the location.

**Comment by darkquasar** [comment]
This is not a bug but a feature. BestiaPop does not generate two files, it generates a file for each lat/lon slice and, at the end, it generates a file containing **all** the lat/lon called `bestiapop-beastly-dataframe.csv`. Perhaps you have seen only two files because you ran the app with a single combination of lat/lon. 

The purpose of generating the final CSV is to make it easier to import into things like Jupyter Notebooks when doing data analysis, rather than having to import each individual file (combination of lat/lon). This is also useful if you would like to see all the data you've downloaded in a excel spreadsheet, instead of having to copy/paste from each individual file.

Let me know what your thoughts are

**Comment by JJguri** [comment]
All good with this. I did not realise this feature was activated. In fact, it is a great idea. We should add a single description of this in the documentation, otherwise, users do not know why the complete file is generated and the purposes of it.

**Comment by darkquasar** [comment]
fixed documentation in commit 70e097d
