### ISSUE TITLE
decimals in WHT files

### ISSUE THREAD

**Issue by JJguri** [JJguri/bestiapop#33]
bestiapop is generating data with one and zero decimals depend on the values of the variables. When the datum does not have decimals, bestiapop should add a zero, i.e. all data should have 1 decimal value.

**Comment by darkquasar** [comment]
Ok this can be fixed, but it would be easier if I could add two decimals after the dot so that an apparently integer value of `2` becomes `2.00` instead of `2.0`. The latter would require a bit more work. 

I believe we should test the WHT files in DSSAT somehow so that we can evaluate whether pure integers in the file are an actual issue or not.

**Comment by JJguri** [comment]
I checked the WTH files in DSSAT. The decimal numbers are not an issue, please leave one decimal when there is a decimal, otherwise an integer. Regarding the INSI parameter, it needs to be 4 digits. Use whatever you want there, as far I know the model is not using this for any process.

**Comment by darkquasar** [comment]
done, fixed in commit af101ee
