### ISSUE TITLE
The code is generating empty MET files

### ISSUE THREAD

**Issue by JJguri** [JJguri/bestiapop#8]
the code is creating METs for empty cells (only the cells that cover land have data). Probably an exemption line needs to be added somewhere to avoid the generation of empty files.
I downloaded 91 files of 128 years each and it took 5 hs 48 min and 40 sec to download this selection of grids. It means an efficiency of 3.8 min/file. If you want to download the entire agricultural areas in Tasmania at once (1730 grids), it will take 110 hs approx just considering the grids that cover the land. I am not sure how much this efficiency will be improved avoiding the creation of these empty files. There are grids that do not have any data, so the code should be able to sense that from the first year and not iterate again for the following years again due to they are empty also.

**Comment by darkquasar** [comment]
I know how to fix this, but it can be fixed in many ways. So, I have two questions for you:

**a.** can we safely assume that if there is a *null* value for a given day in the year (in some lat-lon combination) then values will be "null" for ALL the rest of the days in that year? i.e. for combination `LAT -41.15 LON 144.6 VARIABLE daily_rain YEAR 2018` the first day of the year has a null value, can I assume that the rest of the values will also be null?

**b.** can we safely assume that, if there were no values for a given lat-lon combination for a climate variable, that then the rest of the climate variables will ALSO be null in that exact same lat-lon combination? i.e. for combination `LAT -41.15 LON 144.6 VARIABLE daily_rain YEAR 2018` all days are *null*, can I then assume that the same will apply to variables **max_temp, min_temp, radiation** *in the same year*, etc?

If these two assumptions are correct, then I can modify the code so as to keep track of all the lat-lon combinations where there were no values for a given year and remove them from the range of latitutes and longitudes that are used to generate *MET files*. Not only that but we could increase the performance of the code by simply sampling the first year of a series and skipping the whole series instead of having to *confirm* that there are no values in *all of the days* for a given year.

**Comment by JJguri** [comment]
**Answer for the method (a):** yes, we can safely assume that if there is a null value for a given day in the year (in some lat-lon combination) then values will be "null" for ALL the rest of the days in that year. See the example below for LAT -41.15 LON 144.6 VARIABLE max_temp YEAR 2018.
![image](https://user-images.githubusercontent.com/41041705/81052156-506b3380-8f06-11ea-8d93-a5470e34169f.png)

**Answer for the method (b):** we can safely assume that, if there were no values for a given lat-lon combination for a climate variable, that then the rest of the climate variables will ALSO be null in that exact same lat-lon combination. See the example below for LAT -41.15 LON 144.6 VARIABLE daily_rain YEAR 2018.
![image](https://user-images.githubusercontent.com/41041705/81052235-6bd63e80-8f06-11ea-8dcd-5aecf2249e67.png)

**Recommendation:** choose the easiest and fastest method.

**Comment by darkquasar** [comment]
This issue has now been fixed as per commit 177ae4a. I'm going to close the issue but please let me know if this problem persists.
